### ISSUE TITLE
kodi crashed

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/cerberus#8]
Sorry to bother you but the kodi crashed in ubuntu and i tried everything i googled so i was wondering if you can help me in reinstalling kodi in ubuntu.
                                                                            thank you
                                                                               steve

**Comment by NapoleonWils0n** [comment]
Hi Steve, no problem mate

It might be your kodi userdata directory that is the problem, 
so we will remove it and then start kodi and it should create a new kodi userdata directory

1 - Open you file manager in Ubuntu to your home folder

2 - Press control and h on the keyboard to show hidden files

3 - You should see a folder called .kodi, move the .kodi folder to your Desktop

4 - rename the .kodi folder on your desktop to kodi, remove the dot prefix

5 - Try opening Kodi again and see if it doesnt crash, it should create the .kodi folder again in your home directory. Quit Kodi before doing the next step

6 - Copy the git/kodi-playercorefactory/linux/combined/playercorefactory.xml to your kodi userdata directory

7 - If that doesnt work you can try reinstalling Kodi on the command line by running the following command in the terminal

sudo apt install kodi

Let me know if that works

I dont usually check this repo for issue so best to either leave a comment on the kodi forum here, more chance that other users on the forum running Ubuntu might have an answer as well

http://forum.kodi.tv/showthread.php?tid=216111

Or on the kodi-playercorefactory git repo

https://github.com/NapoleonWils0n/kodi-playercorefactory

Otherwise i might miss you message

**Comment by steve55792** [comment]
This is what It says when I try to reinstall it: 
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kodi : Depends: kodi-bin (>= 2:17.0~git20160701.0200-7f6d5cd-0xenial) but 2:17.0~git20160625.0200-d9fd774-0xenial is to be installed
        Recommends: libva-intel-vaapi-driver but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by NapoleonWils0n** [comment]
Hi Steve

I dont know if you are using the ppa or the version of Kodi in the Ubuntu repo if that make s a difference 

http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

a google search for "kodi ubuntu Recommends: libva-intel-vaapi-driver but it is not installable' turns up a few hits

Do mind if we carry on the convesation on the Kodi wiki,
that way other Ubuntu users may be able to help out

http://forum.kodi.tv/showthread.php?tid=216111

**Comment by steve55792** [comment]
Sure, how do we start the conversation in the wiki? Im assuming have to sign up

**Comment by NapoleonWils0n** [comment]
Hi Steve

Yes sign up for the Kodi forum

And then just paste in your comment that started with

This is what It says when I try to reinstall it: 
Building dependency tree

As a new post

**Comment by steve55792** [comment]
okay i clicked on view new posts but it doesnt show where I can start a new posts, unless im having a blonde moment

**Comment by steve55792** [comment]
never mind whatever i did with the kodi wiki  directions, kodi is working now for me, sweeeeeeet.

**Comment by steve55792** [comment]
anyways what would be pretty sweet is in your program is that a person can select all instead of one video at a time to download/record. Dont mind me, I like to think of crazy ideas like that.

**Comment by steve55792** [comment]
i mean also if saving url, ya can save all instead of one at a time

**Comment by NapoleonWils0n** [comment]
Hi Steve

Glad you managed to get it working again, if in doubt bodge it

There isnt a way from within Kodi to select multiple videos to download or to save multiple urls

But you can batch record and find all the iptv links from Kodi on the command line
Watch the videos and read the documentation on github, and you'll be good to go

#### Find iptv links from Kodi with tcpdump ( windump ) and wireshark

https://www.youtube.com/watch?v=ZWsmPaIAJIA

https://www.youtube.com/watch?v=V8hrU7dlzv0

https://www.youtube.com/watch?v=6aojXDxKdAw

#### Batch record videos

https://www.youtube.com/watch?v=t3iMKzCn8wo

#### Documentation on github

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/docs
